import { Inter } from "next/font/google";
import "./globals.css";
import Header from '@/components/header'
import Footer from '@/components/footer'
import { Search, Advertising} from "@/components/main";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Karimoff's Last Exam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <div className="bg-[#2B2B2B]">
        <Header />
        <div className="h-screen flex flex-col justify-between  bg-[#F2F2F2] ">
        <main >
          <Search/>
          <Advertising/>
          {children}
        </main>
        </div>
        <Footer />
        </div>
    </html>
    
  );
}


// container mx-auto px-10 max-w-1240