import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { Search } from "@/components/ui";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Karimoff's Last Exam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
     

        <Header />
        <Search/>

        <main className=" bg-[#F2F2F2]">
          {children}
          </main>
     

        <Footer />
      </body>
    </html>
  );
}

